### PR TITLE
Fixed some bugs with original implementation

### PR DESCRIPTION
**Pull request by FizzBuzz791**
Hi @troyhunt - I've managed to test this locally, found a fixed some bugs;

- `.include` was the wrong operation, changed to `.some` so that results are actually returned.
- class functions needed to have the `static` modifier.
- random selection was using the length of the wrong array.
- random selection could have been operating on an undefined object, defined an empty array.

I believe this should be good now. Can view my debugging efforts here if interested; https://codesandbox.io/s/js-playground-forked-34p349

### CODE REVIEW

**Comment by troyhunt** [comment]
I think we've actually lost a bunch of conditions here @FizzBuzz791, for example the min length and character composition rules. Just me, or do they need to go back in?

**Comment by FizzBuzz791** [comment]
Hrmm, there were some merge/rebase oddities, I thought I resolved them properly though. Let me take another pass :)

**Comment by FizzBuzz791** [comment]
I think I've pulled them all back in now @troyhunt - apologies for the messy PR.

**Comment by troyhunt** [comment]
Just ran it, that's infuriating 🤣

Merged and now live, thanks!

**Comment by FizzBuzz791** [comment]
Brilliant! Glad I could infuriate 😅

**Pull request merged**
