### PR TITLE
Randomise which errors are shown

### PR DESCRIPTION
**Pull request by FizzBuzz791**
I thought it'd be funnier / more infuriating if the errors were randomly shown. I've left a couple of TODO comments indicating a possible future PR where we "rate" the level of infuriation each check might cause and then exhaust the "low" checks first before moving onto the next rating, but that's for another day/person.

### CODE REVIEW

**Comment by troyhunt** [comment]
I _love_ this idea! Not just because it will drive people nuts, but also because it will help us A:B test which ones are the most effective. I'm going to tweak the code a little just to make all the "classic" criteria always show (min length, case, etc) then start throwing the wacky ones at them 😈

**Comment by FizzBuzz791** [comment]
> I _love_ this idea! Not just because it will drive people nuts, but also because it will help us A:B test which ones are the most effective. I'm going to tweak the code a little just to make all the "classic" criteria always show (min length, case, etc) then start throwing the wacky ones at them 😈

Glad you like it! That was my thoughts with adding the "InfurationLevel" to each check. The filtering would become a little more complex, but you'd be able to mark all the "classic" checks as Low and make sure they're all done before moving onto the more wacky checks :)

**Comment by troyhunt** [comment]
I'd love you to have a go at defining those infuriation levels (great term!) such that a typical spammer could solve the first few then start to struggle before it eventually becomes impossible. Just keep gradually levelling it up with a view to giving them hope but ultimately, causing them to fail drastically.

**Comment by FizzBuzz791** [comment]
I'll have a crack this evening.

**Pull request merged**
